defaults:
  - _self_
  - model: microsoft/Phi-3-mini-128k-instruct 
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

seed: 0

wandb: false
wandb_project: knowledge
tags: []
batch_size: 16
test_size: 0.2
val_every: 1000