defaults:
  - _self_
  - specs: standard
  - optim: adamw
  - scheduler: linear_lr
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

seed: 0
model_name: microsoft/Phi-3-mini-128k-instruct 
wandb: false
wandb_project: knowledge
tags: []
batch_size: 4
test_size: 0.1
val_every: 50
epochs: 1
acc_steps: 4
num_workers: 4
log_level: INFO